### PR TITLE
New Plugin: Sharpen

### PR DESCRIPTION
**Pull request by stephan-fischer**
# What's Changing and Why
Added a sharpen plugin.
Please explain and document how to test, or add tests 😉 

## Tasks

- [ x] Add tests
- [x ] Update Documentation
- [ ] Update `jimp.d.ts`
- [ ] Add [SemVer](https://semver.org/) Label

### CODE REVIEW

**Comment by stephan-fischer** [comment]
The tests failed because the gif export - not because the sharpening

**Comment by stephan-fischer** [comment]
@oliver-moran can anybody merge this one?

**Comment by hipstersmoothie** [comment]
Sorry for the delay! I'm getting the repo in order and want to add an easier way to add tests for this. there are tests in the repo but they're really hard to understand. if you want to take a stab at understanding and documenting I be very grateful

**Comment by stephan-fischer** [comment]
@hipstersmoothie  and the plugin will not be merged?

**Comment by damien-ylopo** [comment]
Why was this closed? We need a sharpen function.

**Pull request closed without merging**
