### PR TITLE
Add support of ICO format

### PR DESCRIPTION
**Pull request by andy128k**
# Add support of ICO format

Only encode is implemented.

## Tasks

- [x] Add tests
- [ ] Update Documentation
- [ ] Update `jimp.d.ts`
- [ ] Add [SemVer](https://semver.org/) Label

### CODE REVIEW

**Comment by shtse8** [comment]
any update?

**Comment by hipstersmoothie** [comment]
Sorry I didn't see this. Would it be possible to add encode support with this library? https://www.npmjs.com/package/icojs

**Comment by hipstersmoothie** [comment]
Could we support decode with https://www.npmjs.com/package/icojs?

**Comment by hipstersmoothie** [comment]
No cousin you remake?

**Pull request closed without merging**
