### PR TITLE
Fix Denial of Service vulnerability

### LINKED ISSUE #1003: DoS attack vulnerability
# Expected Behavior

`Jimp.read` promise should be rejected in case of errors.

# Current Behavior

`Jimp.read` throws an error when providing a site with infinite redirect. Can be used to take an app down.

# Failure Information (for bugs)

An uncaught exception is thrown inside Jimp. 

## Steps to Reproduce
Step 1. Run this code and see what happens:
```js
var Jimp = require('jimp');

Jimp.read('https://infinity.👋🏼.ml').then(async (image) => {
  // Code is not necessary here
}).catch((e) => {
  console.error(e);
});
```
 
infinity.👋🏼.ml is a site with infinite redirect. 

**Screenshots**
No screenshots

## Context

- Jimp Version: 0.16.1
- Operating System: Linux
- Node version: 14.15.5

## Failure Logs

```
TypeError: Cannot read property 'toLowerCase' of null
    at phin (/tmp/node_modules/phin/lib/phin.compiled.js:1:744)
    at module.exports (/tmp/node_modules/@jimp/core/dist/request.js:44:5)
    at loadFromURL (/tmp/node_modules/@jimp/core/dist/index.js:104:27)
    at /tmp/node_modules/@jimp/core/dist/index.js:111:14
    at /tmp/node_modules/@jimp/core/dist/request.js:48:9
    at IncomingMessage.<anonymous> (/tmp/node_modules/phin/lib/phin.compiled.js:1:2100)
```

### PR DESCRIPTION
**Pull request by Sly-Little-Fox**
# What's Changing and Why

Just fixing a vulnerability, no changes. Closes #1003.
## What else might be affected

Nothing

## Tasks

- [x] Add tests
- [x] Update Documentation
- [x] Update `jimp.d.ts`
- [ ] Add [SemVer](https://semver.org/) Label

### CODE REVIEW

**Review by Sly-Little-Fox — COMMENTED** [review]
Sorry for changing code style a bit.

**Comment by Sly-Little-Fox** [comment]
@oliver-moran Sorry, had to bump this PR.

**Comment by hipstersmoothie** [comment]
Could you investigate why it's breaking for older node?

**Comment by Sly-Little-Fox** [comment]
> Could you investigate why it's breaking for older node?

What do you mean?

> Could you investigate why it's breaking for older node?

I cannot right now, but can try later.

**Comment by Sly-Little-Fox** [comment]
It fails even on original jimp. It's because of "spread" operator, which is not supported in Node.js 8.

**Comment by hipstersmoothie** [comment]
closing in favor of https://github.com/jimp-dev/jimp/pull/1136

**Pull request closed without merging**
