### PR TITLE
Reset-exif

### LINKED ISSUE #1104: Processed image is rotated from portrait to landscape
# Expected Behavior

Image should preserve the original portrait orientation.

# Current Behavior

Code:

```javascript
const image = await jimp.read(buffer);

const processed = await image.getBufferAsync(jimp.MIME_JPEG);
```

Will change the orientation from portrait to landscape for this image: [IMG_5029.zip](https://github.com/oliver-moran/jimp/files/9910114/IMG_5029.zip)

- Jimp Version: 0.16.1
- Operating System: Ubuntu 22.04
- Node version: 16.18.0

### PR DESCRIPTION
**Pull request by Sarabadu**
# What's Changing and Why
fixes #1104 
After doing the exif rotation, we reset the exif orientation to `1` 

see this commit to compare before and after this changes 48179a17b93165e8fd32a0be2d0cd0d7b973acd9

## What else might be affected
Note: test are still failing because the calculated distance seems quite bigger now (can be the case that the hash is also considering exif metadata in consideration 🤔, should be like that or should only consider the actual image data??)

## Tasks

- [x] Add tests
- [ ] Update Documentation
- [ ] Update `jimp.d.ts`
- [ ] Add [SemVer](https://semver.org/) Label

### CODE REVIEW

**Comment by hipstersmoothie** [comment]
@Sarabadu build isn't working. could you update?

**Comment by Sarabadu** [comment]
@hipstersmoothie added an empty polyfill for the util.inspect used on modify_exif

**Comment by bobzel** [comment]
Is this branch going to be updated further?  The problem it's addressing is very important for making this library be a replacement for Sharp.  I

**Comment by Sarabadu** [comment]
@bobzel this solution was working for my use case and also seems to work on the test, but didn't get more feedback on this.

the solution here uses an apparently unmantained dependency. so not sure if this PR will be merged anyways. i used `modify-exif` after jimp for make it work. hope it helps

**Comment by hipstersmoothie** [comment]
@Sarabadu I'd merge if the tests pass :D

**Comment by Sarabadu** [comment]
> @Sarabadu I'd merge if the tests pass :D

@hipstersmoothie, as i mentioned in the description,  the issue with the test is the calculated distance is also calculating exif information.

not sure how to solve that tbh, changing the expected distance values doesn't give much value, I think, any suggestion? remove those tests? any idea how to solve this on the distance function(seems like a breaking changes) ?

WDYT?

**Comment by Sarabadu** [comment]
@hipstersmoothie in case you miss it i made the changes to the tests, feel free to run the CI

**Comment by hipstersmoothie** [comment]
@Sarabadu Hey! I'm currently working on a major rewrite of everything and your changes are already included. No tba, still have a few things to figure out

**Comment by Sarabadu** [comment]
Glad to hear @hipstersmoothie In that case feel free to close this PR.

If you are doing
A mayor rewrite, maybe you can also try to not use the `modify-exif` too

**Comment by hipstersmoothie** [comment]
I'm not sure what that means but feel free to make a pr to the v1 branch !

**Comment by Sarabadu** [comment]
closing it as seems it will be solved in the rewrite

**Pull request closed without merging**
